import { config } from 'dotenv'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
config({ path: resolve(dirname(fileURLToPath(import.meta.url)), '../../.env') })

import mongoose from 'mongoose'
import Treatment from '../models/Treatment.js'

const treatments = [
  {
    slug: 'dental-implants',
    name: 'Dental Implants',
    tagline: 'Permanent. Natural-looking. Life-changing.',
    priceFrom: '£2,500',
    priceNote: 'Single implant from £2,500. Full treatment cost provided at free consultation.',
    financeAvailable: true,
    h1: 'Dental Implants in Godalming',
    title: 'Dental Implants Godalming Surrey | Octavia Dental',
    metaDesc: 'Expert dental implants in Godalming. Dr Ali is our implant specialist. Permanent tooth replacement from £2,500. Free consultation. Serving Surrey & Hampshire.',
    heroImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=1200&q=80',
    specialist: 'dr-ali',
    gdcNote: false,
    rxNote: false,
    order: 1,
    whatIsIt: [
      'A dental implant is a small titanium post placed into your jawbone to act as an artificial tooth root. Once it has bonded with the bone — a process called osseointegration — a natural-looking crown is attached on top, giving you a permanent, stable replacement for a missing tooth.',
      'Unlike dentures, implants do not slip or require removal at night. Unlike bridges, they do not require the grinding down of adjacent healthy teeth. The result is a tooth that looks, feels and functions exactly like your natural dentition.',
      'At Octavia Dental, all implant treatment is carried out by Dr Ali, our specialist with extensive postgraduate training in implant dentistry. We use only premium-grade implant systems with long-term clinical track records.',
    ],
    benefits: [
      'Permanent solution — can last 20+ years with proper care',
      'Looks and feels like a natural tooth',
      'Prevents bone loss in the jaw',
      'No impact on adjacent healthy teeth',
      'No removal, no adhesives, no dietary restrictions',
      'Improves speech and chewing confidence',
    ],
    process: [
      { step: 1, title: 'Free consultation', body: 'Dr Ali assesses your bone density, gum health, and overall suitability. You receive a personalised treatment plan and transparent quote at no cost.' },
      { step: 2, title: 'Implant placement', body: 'Under local anaesthetic, the titanium implant post is placed into the jawbone. Most patients report far less discomfort than expected.' },
      { step: 3, title: 'Healing period', body: 'Over 8–12 weeks, the implant fuses with your bone (osseointegration). A temporary restoration keeps your smile looking natural during this time.' },
      { step: 4, title: 'Crown fitting', body: 'Once the implant has fully integrated, a custom-made porcelain crown is attached — matched precisely to the colour and shape of your surrounding teeth.' },
      { step: 5, title: 'Aftercare', body: 'You receive a follow-up appointment and an aftercare plan. With regular hygiene visits and normal brushing, your implant should last a lifetime.' },
    ],
    faq: [
      { q: 'Are dental implants painful?', a: 'Most patients report less discomfort than expected. The procedure is carried out under local anaesthetic so you feel no pain during treatment. Some mild soreness for a few days afterwards is normal and easily managed with over-the-counter pain relief.' },
      { q: 'How long do dental implants last?', a: 'With proper care, dental implants can last 20 years or more. Many last a lifetime. Good oral hygiene and regular check-ups are the key factors.' },
      { q: 'Am I a candidate for dental implants?', a: 'Most adults with good general health are suitable candidates. Dr Ali will assess your bone density, gum health and overall oral health at your free consultation. Even patients who have been told elsewhere they are not suitable may have options — please book to find out.' },
      { q: 'How much do dental implants cost in Godalming?', a: 'A single dental implant at Octavia Dental starts from £2,500. Dr Ali will provide a full personalised quote at your free consultation.' },
      { q: 'How long does the implant process take?', a: 'The full process typically takes 3–6 months, allowing time for the implant to integrate with the jawbone. Some patients are eligible for same-day teeth procedures — Dr Ali will advise at consultation.' },
      { q: 'Can I get implants if I have had bone loss?', a: 'Bone grafting can often restore sufficient bone volume for implant placement. Dr Ali will assess your X-rays and CBCT scan at consultation and advise on your individual situation.' },
    ],
  },
  {
    slug: 'invisalign',
    name: 'Invisalign',
    tagline: 'Straighten your smile — invisibly.',
    priceFrom: 'Free consultation',
    priceNote: 'Comprehensive cases typically £2,800–£5,000. Exact cost confirmed at free consultation.',
    financeAvailable: true,
    h1: 'Invisalign in Godalming',
    title: 'Invisalign Godalming Surrey | Clear Braces | Octavia Dental',
    metaDesc: 'Invisalign clear aligners in Godalming, Surrey. Free consultation. Straighten your teeth without anyone knowing. Serving Guildford, Farnham, Haslemere & Hampshire.',
    heroImage: 'https://images.unsplash.com/photo-1571772996211-2f02c9727629?auto=format&fit=crop&w=1200&q=80',
    specialist: 'dr-ana',
    gdcNote: false,
    rxNote: false,
    order: 2,
    whatIsIt: [
      'Invisalign is the world\'s leading clear aligner system, used to straighten teeth gradually using a series of custom-made, removable trays. Each tray is worn for approximately two weeks before progressing to the next, gently shifting your teeth into the desired position.',
      'Unlike traditional metal braces, Invisalign aligners are virtually invisible when worn, making them the preferred choice for adults and teenagers who want to improve their smile discreetly. There are no brackets to catch food and no wires to irritate your gums.',
      'At Octavia Dental, Dr Ana uses the latest iTero scanning technology to create a precise digital model of your teeth, allowing you to preview your expected results before treatment even begins.',
    ],
    benefits: [
      'Virtually invisible — most people will not notice you are wearing them',
      'Removable — eat, drink and brush normally',
      'No dietary restrictions during treatment',
      'Comfortable smooth plastic — no metal wires or brackets',
      'Digital preview of your expected results before you start',
      'Shorter treatment times than many traditional options',
    ],
    process: [
      { step: 1, title: 'Free consultation', body: 'Dr Ana assesses your teeth, discusses your goals and takes digital photos. She confirms whether Invisalign is right for you and outlines the expected timeline.' },
      { step: 2, title: 'Digital scan & treatment planning', body: 'A precise 3D iTero scan replaces messy impressions. You can see a simulation of your final smile before committing to treatment.' },
      { step: 3, title: 'Receive your aligners', body: 'Your custom aligner series arrives, usually within 2–3 weeks. Dr Ana fits your first trays and explains how to wear and care for them.' },
      { step: 4, title: 'Progress check-ups', body: 'Regular short appointments every 6–8 weeks to monitor your progress and hand over your next batch of aligners.' },
      { step: 5, title: 'Retainers', body: 'Once treatment is complete, a retainer is provided to maintain your new smile. This is an essential part of keeping your teeth in their corrected position long-term.' },
    ],
    faq: [
      { q: 'How long does Invisalign take?', a: 'Most cases take 6–18 months depending on complexity. Mild corrections can be completed in as little as 3 months. Dr Ana will give you an accurate timeline at your free consultation.' },
      { q: 'Can I eat and drink with Invisalign?', a: 'You remove your aligners to eat and drink anything other than water, so there are no dietary restrictions. Simply remove, eat, brush, and replace.' },
      { q: 'Is Invisalign noticeable?', a: 'Invisalign aligners are virtually invisible. Most people — including friends and colleagues — will not notice you are wearing them.' },
      { q: 'How much does Invisalign cost?', a: 'Invisalign at Octavia Dental is priced following your free consultation when we assess complexity. Comprehensive cases typically range from £2,800 to £5,000. We offer flexible payment plans — ask at your consultation.' },
      { q: 'How is Invisalign different from traditional braces?', a: 'Unlike fixed braces, Invisalign aligners are removable, virtually invisible, and more comfortable. There are no metal brackets or wires. You can remove them for eating, sports and special occasions.' },
      { q: 'What happens if I lose an aligner?', a: 'Contact us as soon as possible. We can order a replacement or advise you to move to your next aligner, depending on where you are in your treatment. It happens more than you think and we\'ll manage it easily.' },
    ],
  },
  {
    slug: 'composite-bonding',
    name: 'Composite Bonding',
    tagline: 'Transform your smile in a single appointment.',
    priceFrom: '£250 per tooth',
    priceNote: 'From £250 per tooth. Full smile makeovers from £1,800. Prices confirmed at free consultation.',
    financeAvailable: false,
    h1: 'Composite Bonding in Godalming',
    title: 'Composite Bonding Godalming Surrey | Same-Day Smile | Octavia Dental',
    metaDesc: 'Composite bonding in Godalming from £250 per tooth. Same-day treatment, no drilling. Cosmetic dentist Dr Ana. Serving Surrey & Hampshire. Book free consultation.',
    heroImage: 'https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=1200&q=80',
    specialist: 'dr-ana',
    gdcNote: false,
    rxNote: false,
    order: 3,
    whatIsIt: [
      'Composite bonding is a cosmetic dental treatment in which a tooth-coloured resin material is applied directly to the surface of your teeth and sculpted by hand to correct chips, gaps, discolouration, uneven lengths or shape irregularities.',
      'The treatment requires no drilling in most cases and no anaesthetic — meaning it is completely pain-free for the vast majority of patients. It can typically be completed in a single appointment, making it one of the most time-efficient smile transformation options available.',
      'Dr Ana is highly skilled in freehand composite artistry, building each tooth layer by layer and polishing to a lifelike finish that blends seamlessly with your natural teeth.',
    ],
    benefits: [
      'Same-day results — often completed in a single 1–3 hour appointment',
      'No drilling or injections required in most cases',
      'Completely reversible — no tooth structure is removed',
      'Corrects chips, gaps, discolouration and uneven teeth',
      'Matched precisely to your natural tooth colour',
      'One of the most affordable cosmetic treatments available',
    ],
    process: [
      { step: 1, title: 'Free consultation', body: 'Dr Ana discusses your smile goals and assesses your teeth. She explains what composite bonding can achieve for your specific situation and provides a clear quote.' },
      { step: 2, title: 'Shade matching', body: 'The composite resin is carefully matched to your existing tooth colour and translucency, ensuring the result looks completely natural.' },
      { step: 3, title: 'Surface preparation', body: 'The tooth surface is gently etched with a mild acid to help the resin bond securely. This is painless and preserves all of your natural tooth structure.' },
      { step: 4, title: 'Bonding & sculpting', body: 'Dr Ana applies the resin layer by layer, sculpting each tooth by hand to achieve the desired shape, length and contour.' },
      { step: 5, title: 'Polish & review', body: 'The composite is polished to a smooth, natural finish. You\'ll review the results together and any final adjustments are made before you leave.' },
    ],
    faq: [
      { q: 'Does composite bonding hurt?', a: 'Composite bonding is a pain-free treatment. No injections or drilling are required in most cases. Some patients with sensitive teeth may feel mild sensitivity, which we can manage easily.' },
      { q: 'How long does composite bonding last?', a: 'With good care, composite bonding lasts 5–7 years. Avoiding hard foods such as ice or hard sweets, and wearing a night guard if you grind your teeth, will significantly extend its life.' },
      { q: 'Does composite bonding damage your teeth?', a: 'No. Composite bonding is one of the most conservative cosmetic treatments available. It adds material to your teeth rather than removing tooth structure, making it fully reversible.' },
      { q: 'How many teeth can be bonded in one visit?', a: 'Most patients have between 2 and 8 teeth bonded in a single appointment, typically taking 1–3 hours depending on the number of teeth.' },
      { q: 'What is the difference between composite bonding and veneers?', a: 'Composite bonding uses tooth-coloured resin applied directly to the tooth — reversible, same-day and lower cost. Porcelain veneers are thin ceramic shells — longer-lasting and stain-resistant, but involve some irreversible tooth preparation.' },
      { q: 'Can composite bonding fix gaps between teeth?', a: 'Yes. Composite bonding is one of the most effective and conservative ways to close small to moderate gaps between teeth without orthodontics.' },
    ],
  },
  {
    slug: 'veneers',
    name: 'Porcelain Veneers',
    tagline: 'Perfection crafted in porcelain.',
    priceFrom: '£800 per tooth',
    priceNote: 'From £800 per tooth. Full veneer cases from £4,800. Exact costs at free consultation.',
    financeAvailable: true,
    h1: 'Porcelain Veneers in Godalming',
    title: 'Porcelain Veneers Godalming Surrey | Octavia Dental',
    metaDesc: 'Porcelain veneers in Godalming from £800 per tooth. Expert cosmetic dentist Dr Ana. Natural-looking, long-lasting results. Free consultation.',
    heroImage: 'https://images.unsplash.com/photo-1629909615184-74f495363b67?auto=format&fit=crop&w=1200&q=80',
    specialist: 'dr-ana',
    gdcNote: false,
    rxNote: false,
    order: 4,
    whatIsIt: [
      'Porcelain veneers are ultra-thin ceramic shells, custom-crafted to bond to the front surface of your teeth. They are designed to permanently correct colour, shape, alignment and proportion, creating a smile that is both radiant and completely natural in appearance.',
      'Unlike composite bonding, porcelain veneers are fabricated in a dental laboratory to millimetre precision. The result is exceptional translucency and a stain-resistant surface that maintains its brightness for many years.',
      'At Octavia Dental, Dr Ana takes a highly personalised approach to veneer design. Using a diagnostic wax-up, you can preview your new smile before any preparation begins, ensuring the outcome exceeds your expectations.',
    ],
    benefits: [
      'Long-lasting — porcelain veneers typically last 10–15 years',
      'Stain-resistant surface that stays bright',
      'Exceptional translucency — mimics natural tooth enamel',
      'Corrects colour, shape, alignment and proportion',
      'Custom-crafted in a specialist dental laboratory',
      'Can transform multiple issues in one treatment',
    ],
    process: [
      { step: 1, title: 'Consultation & smile design', body: 'Dr Ana discusses your goals, takes photos and scans, and designs your veneers using a digital mockup so you can preview your result before committing.' },
      { step: 2, title: 'Tooth preparation', body: 'A small amount of enamel (typically 0.3–0.5mm) is removed from the front of each tooth to create space for the veneer. Local anaesthetic ensures this is comfortable.' },
      { step: 3, title: 'Impressions & temporaries', body: 'Precise impressions are taken and sent to our ceramist. Temporary veneers are fitted so you are never without a complete smile while your permanent veneers are crafted.' },
      { step: 4, title: 'Veneer fitting', body: 'At your fitting appointment, each veneer is checked for fit, colour and shape, and bonded permanently to your teeth using a light-cured dental adhesive.' },
      { step: 5, title: 'Review appointment', body: 'A short follow-up appointment 1–2 weeks later checks your bite and ensures you are completely happy with the result.' },
    ],
    faq: [
      { q: 'Are porcelain veneers permanent?', a: 'Because a small amount of enamel is removed during preparation, veneers are considered a long-term commitment. The veneers themselves last 10–15 years and can be replaced when needed.' },
      { q: 'Do veneers look natural?', a: 'When designed well, porcelain veneers are indistinguishable from natural teeth. The ceramist matches the colour, translucency and texture of your surrounding teeth precisely.' },
      { q: 'How much do porcelain veneers cost in Godalming?', a: 'Porcelain veneers at Octavia Dental start from £800 per tooth. A full smile makeover typically involves 6–10 veneers. Dr Ana provides a detailed quote at your free consultation.' },
      { q: 'Can I get veneers on just a few teeth?', a: 'Yes. Veneers can be placed on as few as one tooth if needed. Dr Ana will ensure the colour and shape complement your natural teeth seamlessly.' },
      { q: 'How do I care for my veneers?', a: 'Veneers require the same care as natural teeth — brushing, flossing and regular hygiene visits. Avoiding biting directly into very hard foods and wearing a night guard if you grind will significantly extend their life.' },
    ],
  },
  {
    slug: 'teeth-whitening',
    name: 'Teeth Whitening',
    tagline: 'A brighter smile — safely.',
    priceFrom: '£299',
    priceNote: 'In-surgery whitening from £399. Home whitening kits from £299. Combination packages available.',
    financeAvailable: false,
    h1: 'Teeth Whitening in Godalming',
    title: 'Teeth Whitening Godalming Surrey | Professional | Octavia Dental',
    metaDesc: 'Professional teeth whitening in Godalming from £299. In-surgery and home kits available. Dramatically whiter teeth in one visit.',
    heroImage: 'https://images.unsplash.com/photo-1559599076-9b6f425d1b07?auto=format&fit=crop&w=1200&q=80',
    specialist: 'dr-ana',
    gdcNote: false,
    rxNote: false,
    order: 5,
    whatIsIt: [
      'Professional teeth whitening is the safest, most effective way to lighten the natural colour of your teeth without damaging them. At Octavia Dental, we offer both in-surgery whitening (results in a single appointment) and custom home whitening kits, depending on your lifestyle and goals.',
      'Over-the-counter whitening products available in shops are limited by law to concentrations so low they have minimal effect. Professional whitening uses clinically proven concentrations of hydrogen or carbamide peroxide that can lighten teeth by several shades safely.',
      'Dr Ana takes impressions of your teeth to create custom-fitted whitening trays for your home kit, ensuring even coverage and minimising gum sensitivity — the most common side effect of poorly-fitted generic trays.',
    ],
    benefits: [
      'Noticeable results in a single visit or within 2 weeks of home use',
      'Safe, clinically proven concentrations — not available over the counter',
      'Custom-fitted trays for even, comfortable whitening',
      'Can lighten teeth by 4–8 shades',
      'Long-lasting results with simple maintenance',
      'Can be combined with composite bonding or veneers for a complete smile makeover',
    ],
    process: [
      { step: 1, title: 'Shade assessment', body: 'Dr Ana photographs your teeth and uses a shade guide to record your current colour. This allows you to measure your results accurately.' },
      { step: 2, title: 'Custom tray impressions', body: 'Precise impressions are taken to create whitening trays that fit your teeth exactly — this is what makes professional whitening so much more effective than generic kits.' },
      { step: 3, title: 'Whitening treatment', body: 'For in-surgery whitening, a professional-strength gel is applied and activated. For home kits, you wear your custom trays for the prescribed time each day over 2 weeks.' },
      { step: 4, title: 'Review & top-up', body: 'Dr Ana reviews your results and provides top-up gel to maintain your shade. Results typically last 12–18 months with good maintenance.' },
    ],
    faq: [
      { q: 'Is professional teeth whitening safe?', a: 'Yes. Professional whitening carried out by a GDC-registered dentist is safe. The concentrations used are carefully calibrated to whiten effectively without causing enamel damage.' },
      { q: 'How many shades whiter can I expect?', a: 'Most patients achieve 4–8 shades of whitening, depending on the starting shade and type of staining. Dr Ana will give you a realistic expectation at your consultation.' },
      { q: 'Does teeth whitening cause sensitivity?', a: 'Some temporary sensitivity is common during treatment. Dr Ana uses formulas with added desensitising agents and will advise on how to minimise any discomfort.' },
      { q: 'How long do results last?', a: 'Professional whitening results typically last 12–18 months, depending on lifestyle factors such as tea, coffee, wine and smoking. Top-up gel is available to maintain your shade.' },
      { q: 'Can I whiten crowns or veneers?', a: 'Whitening gel only affects natural tooth enamel — it cannot change the shade of crowns, veneers or bonding. Dr Ana will advise if any restorations would need replacing to match your new shade.' },
      { q: 'Is over-the-counter whitening as effective?', a: 'No. UK law limits over-the-counter products to 0.1% hydrogen peroxide — a concentration so low it has very limited effect. Professional whitening uses clinically proven concentrations that are only available through a registered dental professional.' },
    ],
  },
  {
    slug: 'six-month-smile',
    name: '6 Month Smile',
    tagline: 'A straighter smile in as little as 6 months.',
    priceFrom: '£2,000',
    priceNote: 'From £2,000 depending on complexity. Full quote provided at free consultation.',
    financeAvailable: false,
    h1: '6 Month Smile in Godalming',
    title: '6 Month Smile Godalming Surrey | Short-Term Braces | Octavia Dental',
    metaDesc: '6 Month Smile orthodontics in Godalming. Straighten your front teeth in as little as 6 months using clear braces. Free consultation.',
    heroImage: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=1200&q=80',
    specialist: 'dr-ana',
    gdcNote: false,
    rxNote: false,
    order: 6,
    whatIsIt: [
      '6 Month Smile is a short-term orthodontic system specifically designed to straighten the front teeth — the teeth you see when you smile — in a fraction of the time taken by traditional braces. Most cases are completed in just 4–9 months.',
      'The system uses tooth-coloured brackets and clear wires that are far less visible than conventional metal braces. Unlike Invisalign, 6 Month Smile brackets are fixed in place, meaning no discipline is required in wearing them — they work continuously, every hour of every day.',
      'At Octavia Dental, Dr Ana uses 6 Month Smile for patients who want a faster orthodontic result than Invisalign offers, or who prefer fixed appliances. It is particularly suited to adults who have relapsed after previous orthodontic treatment.',
    ],
    benefits: [
      'Faster results than traditional orthodontics — typically 4–9 months',
      'Tooth-coloured brackets and wires — far less visible than metal braces',
      'Fixed appliance — no need to remember to wear trays',
      'Works on the cosmetic zone — the teeth that matter for your smile',
      'Lower cost than comprehensive Invisalign treatment',
      'Suitable for adults who have had previous orthodontic relapse',
    ],
    process: [
      { step: 1, title: 'Free consultation', body: 'Dr Ana assesses your teeth and bite, takes photos and scans, and confirms whether 6 Month Smile is the right treatment for your situation.' },
      { step: 2, title: 'Records & treatment planning', body: 'Detailed records are taken and submitted to the 6 Month Smile lab, which produces a customised bracket prescription for your specific tooth movements.' },
      { step: 3, title: 'Bracket placement', body: 'Dr Ana bonds the tooth-coloured brackets to your teeth and threads the clear wire. The appointment takes approximately 60–90 minutes.' },
      { step: 4, title: 'Monthly adjustments', body: 'Regular short appointments every 4–6 weeks to adjust the wire tension and monitor progress. Treatment averages 4–9 months.' },
      { step: 5, title: 'Debond & retainers', body: 'When your teeth have reached their final position, the brackets are removed and a retainer is provided to maintain your result long-term.' },
    ],
    faq: [
      { q: 'Will people notice I\'m wearing 6 Month Smile braces?', a: 'The tooth-coloured brackets and clear wires are significantly less noticeable than traditional metal braces. Most patients report that friends and colleagues do not notice unless told.' },
      { q: 'Does 6 Month Smile hurt?', a: 'Some soreness for 2–3 days after each adjustment appointment is normal, as with any orthodontic treatment. Over-the-counter pain relief manages this easily.' },
      { q: 'Can I eat normally with 6 Month Smile?', a: 'You should avoid very hard or sticky foods that could damage the brackets. Other than that, your diet is largely unrestricted.' },
      { q: 'Is 6 Month Smile or Invisalign better for me?', a: 'It depends on your teeth and lifestyle. 6 Month Smile is fixed so you never forget to wear it; Invisalign is removable and invisible. Dr Ana will recommend the most appropriate option at your consultation.' },
      { q: 'How much does 6 Month Smile cost?', a: '6 Month Smile at Octavia Dental starts from £2,000 depending on complexity. Dr Ana will provide an exact quote at your free consultation.' },
    ],
  },
  {
    slug: 'air-flow-hygiene',
    name: 'Air Flow Hygiene',
    tagline: 'The deepest clean your teeth have ever had.',
    priceFrom: '£99',
    priceNote: 'Air Flow hygiene appointment from £99. Combined with stain removal from £129.',
    financeAvailable: false,
    h1: 'Air Flow Hygiene in Godalming',
    title: 'Air Flow Hygiene Godalming | Advanced Dental Cleaning | Octavia Dental',
    metaDesc: 'Air Flow advanced hygiene treatment in Godalming. Deeper, fresher clean than standard scale and polish. Book your appointment today.',
    heroImage: 'https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=1200&q=80',
    specialist: 'dr-ana',
    gdcNote: false,
    rxNote: false,
    order: 7,
    whatIsIt: [
      'Air Flow is an advanced dental hygiene system that uses a controlled stream of compressed air, warm water and fine powder particles to remove plaque, staining, discolouration and early calculus from the surfaces of your teeth and beneath the gum line.',
      'Unlike traditional scale and polish techniques, Air Flow technology can clean areas that are difficult or impossible to reach with conventional instruments — including between teeth, around orthodontic brackets and beneath the gum line — without contact, heat or discomfort.',
      'The treatment leaves teeth feeling exceptionally clean and noticeably brighter, as surface staining from tea, coffee, wine and tobacco is removed efficiently. Many patients describe it as the best clean they have ever experienced.',
    ],
    benefits: [
      'Removes staining, plaque and early calculus in one appointment',
      'Reaches areas traditional cleaning cannot — including under the gum line',
      'Gentle and comfortable — no scraping sensation',
      'Leaves teeth visibly brighter by removing surface staining',
      'Reduces risk of gum disease and early decay',
      'Suitable for patients with implants, orthodontic appliances and sensitive teeth',
    ],
    process: [
      { step: 1, title: 'Oral health assessment', body: 'Dr Ana reviews your gum health, charts any areas of concern and confirms Air Flow is appropriate for your needs.' },
      { step: 2, title: 'Air Flow treatment', body: 'A controlled stream of fine powder, water and air is directed across all tooth surfaces and just beneath the gum line, removing plaque, stain and early calculus gently and thoroughly.' },
      { step: 3, title: 'Ultrasonic scaling (if needed)', body: 'Any calculus (tartar) that is too hardened for Air Flow alone is removed with an ultrasonic scaler — a much more comfortable alternative to traditional hand instruments.' },
      { step: 4, title: 'Polish & fluoride', body: 'Teeth are polished to a smooth finish and fluoride is applied to strengthen enamel and reduce sensitivity.' },
    ],
    faq: [
      { q: 'Is Air Flow better than a standard scale and polish?', a: 'Air Flow reaches areas that standard cleaning cannot — particularly between teeth and beneath the gum line — and removes staining far more effectively. Most patients prefer it for both comfort and results.' },
      { q: 'Is Air Flow painful?', a: 'Air Flow is comfortable for the vast majority of patients, particularly compared to traditional hand scaling. Some patients with sensitive teeth notice mild sensitivity to the water temperature, which we manage easily.' },
      { q: 'How often should I have Air Flow?', a: 'Most patients benefit from an Air Flow appointment every 6 months as part of their routine hygiene care. Patients with a history of gum disease or heavy staining may benefit from more frequent visits.' },
      { q: 'Will Air Flow whiten my teeth?', a: 'Air Flow removes surface staining very effectively, which can make teeth appear noticeably brighter. It does not chemically whiten teeth — for a long-lasting shade change, professional teeth whitening is the appropriate treatment.' },
      { q: 'Is Air Flow suitable if I have implants or braces?', a: 'Yes. Air Flow is particularly well-suited to patients with implants, fixed orthodontic appliances or bridges, as it cleans around these restorations without the risk of damage from metal instruments.' },
    ],
  },
  {
    slug: 'botox-anti-wrinkle',
    name: 'Botox & Anti-Wrinkle',
    tagline: 'Precision aesthetics. Delivered by a dental specialist.',
    priceFrom: '£200',
    priceNote: 'From £200 per area. Full face assessment and pricing at consultation.',
    financeAvailable: false,
    h1: 'Botox & Anti-Wrinkle Injections in Godalming',
    title: 'Botox & Anti-Wrinkle Injections Godalming | Dentist-Led | Octavia Dental',
    metaDesc: 'Botox & anti-wrinkle injections by dentist-trained Dr Ana in Godalming, Surrey. Safer than beauty salons. Natural results. Serving Surrey & Hampshire.',
    heroImage: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1200&q=80',
    specialist: 'dr-ana',
    gdcNote: true,
    rxNote: true,
    order: 8,
    whatIsIt: [
      'Anti-wrinkle injections (commonly known as Botox) work by temporarily relaxing specific facial muscles, softening the appearance of dynamic wrinkles — those caused by repeated muscle movement, such as frown lines, forehead lines and crow\'s feet.',
      'Dentists have a uniquely deep understanding of facial anatomy. Years of training in the structure of muscles, nerves and bones in the head and neck region means Dr Ana can place injections with a precision that most non-medical practitioners cannot replicate.',
      'At Octavia Dental, every patient undergoes a full facial assessment before treatment. We always aim for natural-looking results — our goal is to refresh your appearance, not change it. We never over-treat.',
    ],
    benefits: [
      'Administered by a dental professional with extensive facial anatomy training',
      'Natural-looking results — no frozen or overdone appearance',
      'Treats frown lines, forehead lines and crow\'s feet',
      'Also available for teeth grinding (bruxism) and gummy smile correction',
      'Results visible within 48–72 hours, full effect at 14 days',
      'No downtime — return to normal activities immediately',
    ],
    process: [
      { step: 1, title: 'Facial consultation', body: 'Dr Ana conducts a full facial assessment, discusses your concerns and goals, and advises on the most appropriate treatment. Medical history is reviewed and consent obtained.' },
      { step: 2, title: 'Treatment planning', body: 'Precise injection points are mapped based on your facial anatomy. As a prescription medicine, the treatment plan must meet clinical criteria.' },
      { step: 3, title: 'Injections', body: 'Using ultra-fine needles, Dr Ana places precise micro-injections into the targeted muscles. The process takes approximately 15–20 minutes and most patients describe a mild pinching sensation only.' },
      { step: 4, title: 'Aftercare', body: 'You can return to normal activities immediately. Dr Ana provides clear aftercare instructions and advises on what to avoid for 24 hours after treatment.' },
      { step: 5, title: '2-week review', body: 'A complimentary review appointment at 10–14 days allows Dr Ana to assess your results and make any minor adjustments needed.' },
    ],
    faq: [
      { q: 'Why see a dentist for Botox?', a: 'Dentists have the deepest understanding of facial anatomy — muscles, nerves, and bone structure. Dr Ana has advanced training in facial aesthetics and delivers safer, more precise results than most non-medical practitioners. Dental practices are also regulated by the CQC.' },
      { q: 'How long does Botox last?', a: 'Anti-wrinkle injections typically last 3–4 months. With regular treatment, results can last longer as muscles gradually relax over time.' },
      { q: 'Is Botox painful?', a: 'Most patients describe the sensation as a mild pinch. Dr Ana uses the finest needles available and can apply topical numbing cream if preferred.' },
      { q: 'When will I see results?', a: 'Initial effects appear within 48–72 hours. Full results are visible at 10–14 days, which is why we schedule a review appointment at this point.' },
      { q: 'Are there any side effects?', a: 'Side effects are rare when administered by a trained professional. Temporary redness or mild bruising at the injection site is the most common and resolves within a few days.' },
      { q: 'Can Botox treat teeth grinding?', a: 'Yes. Injections into the masseter muscles (the large jaw muscles) can significantly reduce the force of grinding and clenching, alleviating jaw pain and protecting teeth. This is a growing and highly effective use of anti-wrinkle treatments.' },
    ],
  },
  {
    slug: 'general-dentistry',
    name: 'General Dentistry',
    tagline: 'Preventive, restorative, and routine care — all under one roof.',
    priceFrom: '£65',
    priceNote: 'Check-up from £65. Hygiene appointments from £85. Treatment costs quoted at examination.',
    financeAvailable: false,
    h1: 'General Dentistry in Godalming',
    title: 'General Dentistry Godalming | Check-ups, Fillings & Hygiene | Octavia Dental',
    metaDesc: 'Private general dentistry in Godalming, Surrey. Comprehensive check-ups, white fillings, hygiene appointments, X-rays and emergency dental care. New patients welcome.',
    heroImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=1200&q=80',
    specialist: 'dr-ana',
    gdcNote: false,
    rxNote: false,
    order: 9,
    whatIsIt: [
      'General dentistry forms the foundation of good oral health. At Octavia Dental, our private general dentistry service covers everything you need to maintain healthy teeth and gums — from routine check-ups and hygiene appointments to fillings, X-rays, and emergency care.',
      'As a private practice, we are not restricted by NHS appointment times or treatment options. Every check-up is thorough, unhurried, and personalised — we look beyond the obvious to identify early signs of decay, gum disease, oral cancer, and other conditions that are far easier to treat when caught early.',
      'Whether you are registering as a new patient, looking for a higher standard of routine care, or need urgent dental treatment, our team is here to help.',
    ],
    benefits: [
      'Comprehensive check-ups that go beyond a quick look — includes gum assessment, cancer screening, and X-rays where needed',
      'White composite fillings that match your natural tooth colour',
      'Professional hygiene appointments to remove plaque, tartar, and staining',
      'Digital X-rays with lower radiation exposure and immediate on-screen results',
      'Emergency appointments available for toothache, broken teeth, and lost fillings',
      'Personalised oral health advice tailored to your diet, habits, and dental history',
      'No waiting lists — appointments available at a time that suits you',
    ],
    process: [
      { step: 1, title: 'Comprehensive examination', body: 'We carry out a thorough clinical examination of your teeth, gums, bite, jaw joints, and soft tissues. Digital X-rays are taken where clinically appropriate to detect problems not visible to the naked eye.' },
      { step: 2, title: 'Gum health assessment', body: 'We measure the depth of the pockets around each tooth to assess gum health and identify any early signs of gum disease, which is the leading cause of tooth loss in adults.' },
      { step: 3, title: 'Oral cancer screening', body: 'A systematic check of the tongue, cheeks, lips, floor of the mouth and throat for any unusual changes. Early detection significantly improves outcomes.' },
      { step: 4, title: 'Treatment plan & discussion', body: 'We explain exactly what we have found, show you X-rays and photographs, and discuss all your options — including costs — clearly and without pressure.' },
      { step: 5, title: 'Hygiene & preventive care', body: 'A professional clean removes plaque and tartar that brushing cannot reach. We provide tailored advice on brushing technique, flossing, and any products that could improve your oral health at home.' },
      { step: 6, title: 'Restorative treatment (if needed)', body: 'Any fillings, repairs, or other restorative work are carried out using tooth-coloured materials to achieve a natural result. We always use the most conservative approach to preserve as much natural tooth structure as possible.' },
    ],
    faq: [
      { q: 'Are you accepting new NHS patients?', a: 'We are a private practice and do not provide NHS dental treatment. However, our private check-up and hygiene fees are clearly listed and we provide full cost transparency before any treatment begins.' },
      { q: 'How often should I have a check-up?', a: 'For most patients, every six months is the right interval. Some patients with a history of gum disease, decay, or complex restorations benefit from more frequent visits. We will recommend a personalised recall interval at your first appointment.' },
      { q: 'Do you do white fillings?', a: 'Yes. We use tooth-coloured composite resin for all fillings. We do not place amalgam (silver) fillings. Composite is bonded to the tooth, which means we can preserve more natural tooth structure than with traditional amalgam techniques.' },
      { q: 'What happens at a hygiene appointment?', a: 'Our hygiene appointments include removal of plaque and tartar using ultrasonic and hand instruments, stain removal, polishing, and personalised oral hygiene instruction. We offer standard hygiene and Air Flow advanced hygiene treatments.' },
      { q: 'Can I be seen as an emergency patient?', a: 'Yes. We keep same-day or next-day appointments for patients in pain or with urgent dental needs. Call us on 01483 860020 and we will do everything we can to see you quickly.' },
      { q: 'How much does a check-up cost?', a: 'A comprehensive private check-up at Octavia Dental starts from £65. This includes a full clinical examination, gum assessment, oral cancer screening, and a personalised treatment plan. X-rays are charged separately if required.' },
    ],
  },
]

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI)
  console.log('Connected to MongoDB')

  for (const t of treatments) {
    await Treatment.findOneAndUpdate({ slug: t.slug }, t, { upsert: true, new: true })
    console.log(`Seeded: ${t.name}`)
  }

  console.log('Done — all 9 treatments seeded')
  await mongoose.disconnect()
}

seed().catch(err => { console.error(err); process.exit(1) })
